CREATE TABLE managed_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  original_file_name varchar(255) NOT NULL,
  stored_file_name varchar(255),
  storage_key varchar(600),
  file_extension varchar(12) NOT NULL,
  mime_type varchar(120),
  file_size_bytes bigint NOT NULL CHECK (file_size_bytes >= 0),
  sha256_checksum char(64),
  status varchar(20) NOT NULL CHECK (status IN ('UPLOADING','STORED','FAILED','DELETED')),
  failure_reason varchar(500),
  created_by bigint NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  UNIQUE (workspace_id, id)
);
CREATE INDEX idx_managed_files_history ON managed_files(workspace_id, created_at DESC);
CREATE INDEX idx_managed_files_status ON managed_files(workspace_id, status);
CREATE INDEX idx_managed_files_name ON managed_files(workspace_id, original_file_name);
CREATE UNIQUE INDEX uq_managed_files_active_checksum
  ON managed_files(workspace_id, sha256_checksum) WHERE status = 'STORED';
