-- Outbound calls the CRM will place through the voice agent: visit reminders, due callbacks,
-- re-engagement and first contact with new web/portal leads. A worker claims due rows with
-- FOR UPDATE SKIP LOCKED; idempotency_key is stable per purpose, so a row is never dialled twice
-- and the agent can deduplicate a retried request.
CREATE TABLE scheduled_calls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  lead_id bigint NOT NULL,
  call_type varchar(30) NOT NULL
    CHECK (call_type IN ('OUTBOUND_NEW_LEAD','VISIT_REMINDER','CALLBACK','RE_ENGAGEMENT')),
  due_at timestamptz NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'SCHEDULED'
    CHECK (status IN ('SCHEDULED','DIALING','DONE','CANCELLED','SKIPPED','FAILED')),
  idempotency_key varchar(120) NOT NULL,
  appointment_id bigint,
  callback_id bigint,
  attempts integer NOT NULL DEFAULT 0,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  UNIQUE (idempotency_key),
  FOREIGN KEY (workspace_id, lead_id) REFERENCES leads(workspace_id, id),
  FOREIGN KEY (workspace_id, appointment_id) REFERENCES appointments(workspace_id, id),
  FOREIGN KEY (workspace_id, callback_id) REFERENCES callbacks(workspace_id, id)
);
CREATE INDEX idx_scheduled_calls_due ON scheduled_calls(status, due_at);
CREATE INDEX idx_scheduled_calls_lead ON scheduled_calls(workspace_id, lead_id, due_at);
