-- Actual PDF bytes for a registered property document.
--
-- V1 recorded only metadata and an external storageReference, which meant a brochure could be
-- described in the CRM without the CRM holding it. Files live in the database rather than an
-- object store so a deployment needs no extra infrastructure or credentials; the size ceiling is
-- enforced in the application. Move this to blob storage before the corpus outgrows the database.
CREATE TABLE document_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  document_id bigint NOT NULL,
  filename varchar(260) NOT NULL,
  content_type varchar(120) NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes > 0),
  sha256 char(64) NOT NULL,
  content bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  -- One stored file per document: re-uploading replaces it.
  UNIQUE (workspace_id, document_id),
  FOREIGN KEY (workspace_id, document_id) REFERENCES property_documents(workspace_id, id)
);
CREATE INDEX idx_document_files_document ON document_files(workspace_id, document_id);
