-- Bookable site-visit slots and automatic sales-agent assignment.
--
-- Slots are not stored: they are computed from weekly templates, minus blackouts, minus the
-- capacity already taken by active appointments. A template with project_id NULL is the
-- workspace default for projects that have none of their own.
CREATE TABLE visit_slot_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  project_id bigint,
  day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),  -- ISO: 1 = Monday
  start_time time NOT NULL,
  end_time time NOT NULL,
  slot_minutes integer NOT NULL CHECK (slot_minutes BETWEEN 15 AND 240),
  capacity integer NOT NULL CHECK (capacity BETWEEN 1 AND 100),
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_time > start_time),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, project_id) REFERENCES projects(workspace_id, id)
);
CREATE INDEX idx_visit_slot_templates_scope ON visit_slot_templates(workspace_id, project_id, day_of_week);

-- Holidays and closures. A NULL project blacks out every project in the workspace.
CREATE TABLE visit_slot_blackouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  project_id bigint,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at > starts_at),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, project_id) REFERENCES projects(workspace_id, id)
);
CREATE INDEX idx_visit_slot_blackouts_scope ON visit_slot_blackouts(workspace_id, project_id, starts_at);

-- Which sales agents take visits for a project. last_assigned_at drives round-robin.
CREATE TABLE project_agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  project_id bigint NOT NULL,
  user_id bigint NOT NULL,
  available boolean NOT NULL DEFAULT true,
  last_assigned_at timestamptz,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, project_id, user_id),
  FOREIGN KEY (workspace_id, project_id) REFERENCES projects(workspace_id, id),
  FOREIGN KEY (workspace_id, user_id) REFERENCES workspace_members(workspace_id, user_id)
);
CREATE INDEX idx_project_agents_project ON project_agents(workspace_id, project_id);

-- An agent on leave is skipped for every project at once.
ALTER TABLE workspace_members ADD COLUMN agent_available boolean NOT NULL DEFAULT true;
-- Spoken to customers in visit confirmations ("your agent Riya Desai, 98…").
ALTER TABLE users ADD COLUMN phone varchar(30);
