-- Callbacks a customer, an agent or the system asked for, and the workspace do-not-call list.
CREATE TABLE callbacks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  lead_id bigint NOT NULL,
  due_at timestamptz NOT NULL,
  reason varchar(500),
  requested_by varchar(20) NOT NULL CHECK (requested_by IN ('CUSTOMER','AGENT','SYSTEM')),
  status varchar(20) NOT NULL DEFAULT 'SCHEDULED'
    CHECK (status IN ('SCHEDULED','DIALING','DONE','CANCELLED','FAILED')),
  attempts integer NOT NULL DEFAULT 0,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, lead_id) REFERENCES leads(workspace_id, id)
);
CREATE INDEX idx_callbacks_lead ON callbacks(workspace_id, lead_id, due_at);
CREATE INDEX idx_callbacks_due ON callbacks(status, due_at);

-- Keyed by the last ten digits, the same rule find-or-create uses, so +91 98… and 098… match.
CREATE TABLE dnc_numbers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  phone_tail varchar(10) NOT NULL CHECK (phone_tail ~ '^[0-9]{7,10}$'),
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, id),
  UNIQUE (workspace_id, phone_tail)
);
