import { Link, useParams } from "react-router-dom";
import { useApi } from "../hooks/useApi";
import { useList } from "../hooks/useList";
import {
  Async,
  Badge,
  DataTable,
  Details,
  Filters,
  PageHeader,
  Pagination,
} from "../components/ui";
import { date, label, list } from "../utils/format";
import { CallOutcome } from "../features/voice";
export function Calls() {
  const l = useList("/calls");
  return (
    <>
      <PageHeader
        title="Conversations"
        description="See what your customers said, what matters to them, and what happens next."
      />
      <section className="panel">
        <Filters
          {...l}
          statuses={[
            "QUEUED",
            "IN_PROGRESS",
            "COMPLETED",
            "FAILED",
            "NO_ANSWER",
          ]}
        />
        <Async query={l.query}>
          <DataTable
            data={list(l.query.data)}
            columns={[
              {
                key: "leadName",
                label: "Customer",
                render: (c) => (
                  <Link className="text-link" to={`/calls/${c.id}`}>
                    {c.leadName || "Open conversation"}
                  </Link>
                ),
              },
              {
                key: "createdAt",
                label: "Started",
                render: (c) => date(c.createdAt),
              },
              {
                key: "status",
                label: "Status",
                render: (c) => <Badge value={c.status} />,
              },
              {
                key: "outcome",
                label: "Outcome",
                render: (c) => label(c.outcome),
              },
              {
                key: "mock",
                label: "Service",
                render: (c) =>
                  c.mock ? <Badge value="SIMULATED" /> : "Configured provider",
              },
            ]}
          />
          <Pagination data={l.query.data} page={l.page} setPage={l.setPage} />
        </Async>
      </section>
    </>
  );
}
export function RichContent({ value }: { value: any }) {
  if (value == null || value === "")
    return (
      <p className="text-muted">
        Not available yet. Refresh the conversation to retrieve the latest
        details.
      </p>
    );
  if (typeof value === "string")
    return <div className="content-reader">{value}</div>;
  if (Array.isArray(value))
    return (
      <div className="space-y-3">
        {value.map((v, i) => (
          <div className="transcript-line" key={i}>
            {typeof v === "object" ? (
              <>
                <strong>{v.speaker || v.role || `Entry ${i + 1}`}</strong>
                <p>{v.text || v.content || JSON.stringify(v)}</p>
              </>
            ) : (
              String(v)
            )}
          </div>
        ))}
      </div>
    );
  return <Details data={value} fields={Object.keys(value)} />;
}
export function CallDetail() {
  const { id } = useParams();
  const q = useApi(`/calls/${id}`);
  const d = q.data || {};
  return (
    <>
      <PageHeader
        title="Conversation details"
        back="/calls"
        description={date(d.createdAt)}
      />
      <Async query={q}>
        {d.mock && (
          <div className="demo-strip">
            <strong>Simulated voice session</strong>
            <span>
              This conversation was generated by the demo adapter, not a live
              customer call.
            </span>
          </div>
        )}
        <div className="summary-strip">
          <Badge value={d.status} />
          <span>Outcome: {label(d.outcome)}</span>
          <Link className="text-link" to={`/leads/${d.leadId}`}>
            Open customer record →
          </Link>
          <Link
            className="text-link"
            to={`/handovers?create=true&leadId=${d.leadId}`}
          >
            Prepare handover →
          </Link>
        </div>
        <div className="detail-columns">
          <div className="space-y-6">
            <section className="panel p-6">
              <h2 className="mb-5">Conversation summary</h2>
              <RichContent value={d.summary} />
            </section>
            <CallOutcome call={d} />
            <section className="panel p-6">
              <h2 className="mb-5">Transcript</h2>
              <RichContent value={d.transcript} />
            </section>
          </div>
          <section className="panel p-6 h-fit">
            <h2 className="mb-5">Detected requirements</h2>
            <RichContent value={d.requirements} />
            <div className="mt-6">
              <Details
                data={d}
                fields={[
                  "externalId",
                  "outcome",
                  "handoverStatus",
                  "callbackStatus",
                ]}
              />
            </div>
          </section>
        </div>
      </Async>
    </>
  );
}
